<?php
// Autogenerated from composer.json - All changes will be overridden if generated again!

require_once __DIR__ . "/vendor/autoload.php";

$id = "srcrsmgrc";
$version = "1.2.6";
$ilias_min_version = "5.4.0";
$ilias_max_version = "6.999";
$responsible = "fluxlabs";
$responsible_mail = "support@fluxlabs.ch";
$supports_cli_setup = true;
